# Generated by Django 5.0.4 on 2024-06-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                (
                    "loan_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowers",
                        to="signature.loanagreement",
                    ),
                ),
            ],
        ),
    ]
