# Generated by Django 5.0.4 on 2024-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0002_borrower"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="x_position",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="signature",
            name="y_position",
            field=models.IntegerField(default=50),
        ),
    ]
