# Generated by Django 5.0.4 on 2024-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0003_signature_x_position_signature_y_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="x_position",
            field=models.IntegerField(default=50),
        ),
    ]
