# Generated by Django 5.0.4 on 2024-06-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0004_alter_signature_x_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="x_position",
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name="BorrowerSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature_image", models.ImageField(upload_to="signatures/")),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signature.borrower",
                    ),
                ),
            ],
        ),
    ]
