# Generated by Django 5.0.4 on 2024-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0005_alter_signature_x_position_borrowersignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowersignature",
            name="signed_document",
            field=models.FileField(
                blank=True, null=True, upload_to="signed_documents/"
            ),
        ),
    ]
